package org.marjoriekohn.diningreview.entity;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a restaurant entity in the application.
 * The Restaurant class captures various attributes including the restaurant's name, address.
 * It is uniquely identified by an autogenerated ID and can be
 * associated with multiple reviews.
 *
 * @see org.marjoriekohn.diningreview.entity.Review
 * @see org.marjoriekohn.diningreview.entity.Address
 */

@Entity
@Table(name="restaurant")
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
public class Restaurant {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="restaurant_id")
    private Long restaurantId;
    
    @Column(name="name")
    @NotNull
    private String name;
    
    @Column(name="address")
    @NotNull
    @Embedded
    private Address address;
    
    @OneToMany(mappedBy = "restaurant", cascade = CascadeType.ALL, orphanRemoval = true)
    @JsonManagedReference(value="restaurant-reviews")
    private List<Review> reviews = new ArrayList<>();
}
