package org.marjoriekohn.diningreview.controller;

import jakarta.validation.Valid;
import org.marjoriekohn.diningreview.entity.Restaurant;
import org.marjoriekohn.diningreview.exception.DuplicateRestaurantException;
import org.marjoriekohn.diningreview.service.RestaurantService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.List;

/**
 * Manages RESTful API endpoints for Restaurant-related CRUD operations.
 * The RestaurantController class is mapped to the {@code /restaurants} URI and provides
 * endpoints for adding new restaurants, searching restaurants based on specific criteria,
 * and retrieving restaurant details by ID. It interacts with the RestaurantService to
 * carry out these operations.
 *
 * @see org.marjoriekohn.diningreview.service.RestaurantService
 */
@RestController
@RequestMapping("/restaurants")
public class RestaurantController {
    private final RestaurantService restaurantService;
    @Autowired
    RestaurantController(RestaurantService restaurantService) {
        this.restaurantService = restaurantService;
    }
    
    /**
     * Adds a new restaurant to the database.
     * This endpoint maps to a POST request at {@code /restaurants/new} and creates a new restaurant based on
     * the provided Restaurant. The RestaurantService is used to validate and save the new restaurant. Errors that
     * occur during the creation process are handled by the RestaurantService.
     *
     * @param restaurant an object containing restaurant details, required
     * @return the restaurant that was created
     * @throws DuplicateRestaurantException if a restaurant with the same name and zipcode already exists
     *
     * @see org.marjoriekohn.diningreview.service.RestaurantService#createRestaurant(Restaurant)
     */
    @PostMapping("/new")
    public ResponseEntity<?> addRestaurant(@Valid @RequestBody Restaurant restaurant) {
        Restaurant savedRestaurant = restaurantService.createRestaurant(restaurant);
        return new ResponseEntity<>(savedRestaurant, HttpStatus.CREATED);
    }
    
    /**
     * Retrieves a restaurant by its unique identifier.
     * This endpoint maps to a GET request at {@code /restaurants/{id}} and utilizes the RestaurantService
     * to find the restaurant by its ID. Errors that occur during the retrieval process are handled by the
     * RestaurantService.
     *
     * @param id the autogenerated unique id of the restaurant, required
     * @return the Restaurant with the specified ID and its associated reviews
     *
     * @see org.marjoriekohn.diningreview.service.RestaurantService#findById(Long)
     */
    @GetMapping("/{id}")
    public ResponseEntity<?> getRestaurantById(@PathVariable("id") Long id) {
        Restaurant restaurant = restaurantService.findById(id);
        return new ResponseEntity<>(restaurant, HttpStatus.OK);
    }
    
    /**
     * Searches restaurants based on zipcode and allergy criteria.
     * This endpoint maps to a GET request at {@code /restaurants/search?zipcode=12345&allergy=peanut} and returns a list of restaurants
     * that meet the specified zipcode and allergy criteria. The RestaurantService is used to perform
     * the search and filtering. Errors that occur during the search process are handled by the
     * RestaurantService.
     *
     * @param zipcode the target zipcode, required
     * @param allergy the allergy criteria, required
     * @return a list of Restaurants that meet the criteria and their associated reviews
     *
     * @see org.marjoriekohn.diningreview.service.RestaurantService#searchByZipCodeAndAllergy(String, String)
     */
    @GetMapping("/search")
    public ResponseEntity<?> getRestaurantsByZipcodeAndAllergy(@RequestParam("zipcode") String zipcode, @RequestParam("allergy") String allergy) {
        List<Restaurant> restaurants = restaurantService.searchByZipCodeAndAllergy(zipcode, allergy);
        return new ResponseEntity<>(restaurants, HttpStatus.OK);
    }
}